openapi: 3.0.0
servers:
  - url: 'http://localhost:9090/winecellar/v1'
info:
  version: '1.0'
  title: Wine Cellar
paths:
  /bottles:
    get:
      tags:
        - bottles
      summary: Retrieve all the bottles
      operationId: getBottles
      responses:
        default:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bottle'
      x-contentType: application/json
      x-accepts: application/json
    post:
      security:
        - Roles: []
      tags:
        - bottles
      summary: Add a bottle
      operationId: addBottle
      responses:
        '201':
          description: Success
        '400':
          description: Invalid Bottle input
      x-contentType: application/json
      x-accepts: application/json
      requestBody:
        content:
          application/json:
            schema:
#              $ref: '#/components/schemas/Bottle'
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                  maximum: 20
                name:
                  type: string
                  maxLength: 25
                variety:
                  type: string
                  enum:
                    - Chardonnay
                    - Gewürstraminer
                    - Sauvignon blanc
                year:
                  type: integer
                  format: int32
                quantity:
                  type: integer
                  format: int32
#              additionalProperties: false
  '/bottles/{bottle_id}':
    get:
      tags:
        - bottles
      summary: Retrieve a specific bottle
      operationId: getBottleByBottleId
      parameters:
        - name: bottle_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '404':
          description: Bottle Not Found
        default:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bottle'
      x-contentType: application/json
      x-accepts: application/json
  /information:
    get:
      tags:
        - information
      summary: 'Retrieve information about the cellar like temperature, hygrometry, etc'
      operationId: getCellarInformation
      responses:
        default:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CellarInformation'
      x-contentType: application/json
      x-accepts: application/json
components:
  securitySchemes:
    Roles:
      type: apiKey
      in: header
      name: roles
  schemas:
    Bottle:
      type: object
      properties:
        id:
          type: boolean
#          format: int64
#          maximum: 20
        test:
          type: integer
          format: int32
        name:
          type: string
          maxLength: 10
        variety:
          type: string
          enum:
            - Chardonnay
            - Gewürstraminer
            - Sauvignon blanc
        year:
          type: integer
          format: int32
        quantity:
          type: integer
          format: int32
      additionalProperties: false
    CellarInformation:
      type: object
      properties:
        temparature:
          type: number
          format: float
        hygrometry:
          type: number
          format: float
        availableLocation:
          type: integer
          format: int32
